#!/usr/bin/env bash
# Copy-sync the shared TypeScript client into an app's src/protocol/foaf-client.
set -euo pipefail

if [ "$#" -ne 1 ]; then
  echo "Usage: $0 <path-to-app-repo>" >&2
  exit 1
fi

APP_ROOT="$1"
PACKAGE_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TARGET="$APP_ROOT/src/protocol/foaf-client"

if [ ! -d "$APP_ROOT/src" ]; then
  echo "Target app does not have a src/ directory: $APP_ROOT/src" >&2
  exit 1
fi

mkdir -p "$TARGET"
rsync -a --delete "$PACKAGE_ROOT/src/" "$TARGET/"

while IFS= read -r source_file; do
  temp_file="$(mktemp)"
  {
    echo "// AUTOGENERATED — DO NOT EDIT IN APPS"
    echo "// Source of truth: foaf-client/client/src/${source_file#"$TARGET/"}"
    echo
    awk '!/^\/\/ Source of truth: foaf-client\/client\/src\//' "$source_file"
  } > "$temp_file"
  mv "$temp_file" "$source_file"
  chmod 0644 "$source_file"
done < <(find "$TARGET" -type f \( -name '*.ts' -o -name '*.tsx' \) | sort)

cat > "$TARGET/SOURCE.md" <<'EOF'
# This directory is generated

Source of truth: `foaf-client/client/`.

```bash
./scripts/sync-to-app.sh <path-to-this-app>
```

Do not edit files in this tree. Edit the package and re-sync.
EOF

echo "Synced foaf-client/client/src → $TARGET"
